name: Test Pipeline + Allure Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        run: docker compose up --build --abort-on-container-exit

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget

          wget https://github.com/allure-framework/allure2/releases/download/2.39.0/allure-2.39.0.tgz
          tar -zxvf allure-2.39.0.tgz
          sudo mv allure-2.39.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4


